// flow-typed signature: 50b0dae625de48f3c8d61ba9a347442e
// flow-typed version: <<STUB>>/jsxstyle_v^1.0.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsxstyle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsxstyle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsxstyle/Block' {
  declare module.exports: any;
}

declare module 'jsxstyle/Col' {
  declare module.exports: any;
}

declare module 'jsxstyle/curry' {
  declare module.exports: any;
}

declare module 'jsxstyle/example/Avatar' {
  declare module.exports: any;
}

declare module 'jsxstyle/example/build/bundle' {
  declare module.exports: any;
}

declare module 'jsxstyle/example/LayoutConstants' {
  declare module.exports: any;
}

declare module 'jsxstyle/example/main' {
  declare module.exports: any;
}

declare module 'jsxstyle/example/webpack.config' {
  declare module.exports: any;
}

declare module 'jsxstyle/Flex' {
  declare module.exports: any;
}

declare module 'jsxstyle/Inline' {
  declare module.exports: any;
}

declare module 'jsxstyle/InlineBlock' {
  declare module.exports: any;
}

declare module 'jsxstyle/InlineFlex' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/Addons' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/Color' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/createCSS' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/CSSDisplayNames' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/curry' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/Display' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/explodePseudoStyles' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/extractStyles' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/GlobalStylesheets' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/index' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/JsxstylePlugin' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/legacyAutoprefix' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/makeStyleComponentClass' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/renameClass' {
  declare module.exports: any;
}

declare module 'jsxstyle/lib/webpackLoader' {
  declare module.exports: any;
}

declare module 'jsxstyle/Row' {
  declare module.exports: any;
}

declare module 'jsxstyle/Table' {
  declare module.exports: any;
}

declare module 'jsxstyle/TableCell' {
  declare module.exports: any;
}

declare module 'jsxstyle/TableRow' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/className.spec' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/Color.spec' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/curry.spec' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/example' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/extractStyles.spec' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/renameClass.spec' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/webpackLoader.spec' {
  declare module.exports: any;
}

declare module 'jsxstyle/tests/webpackLoaderNamespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsxstyle/Block.js' {
  declare module.exports: $Exports<'jsxstyle/Block'>;
}
declare module 'jsxstyle/Col.js' {
  declare module.exports: $Exports<'jsxstyle/Col'>;
}
declare module 'jsxstyle/curry.js' {
  declare module.exports: $Exports<'jsxstyle/curry'>;
}
declare module 'jsxstyle/example/Avatar.js' {
  declare module.exports: $Exports<'jsxstyle/example/Avatar'>;
}
declare module 'jsxstyle/example/build/bundle.js' {
  declare module.exports: $Exports<'jsxstyle/example/build/bundle'>;
}
declare module 'jsxstyle/example/LayoutConstants.js' {
  declare module.exports: $Exports<'jsxstyle/example/LayoutConstants'>;
}
declare module 'jsxstyle/example/main.js' {
  declare module.exports: $Exports<'jsxstyle/example/main'>;
}
declare module 'jsxstyle/example/webpack.config.js' {
  declare module.exports: $Exports<'jsxstyle/example/webpack.config'>;
}
declare module 'jsxstyle/Flex.js' {
  declare module.exports: $Exports<'jsxstyle/Flex'>;
}
declare module 'jsxstyle/index' {
  declare module.exports: $Exports<'jsxstyle'>;
}
declare module 'jsxstyle/index.js' {
  declare module.exports: $Exports<'jsxstyle'>;
}
declare module 'jsxstyle/Inline.js' {
  declare module.exports: $Exports<'jsxstyle/Inline'>;
}
declare module 'jsxstyle/InlineBlock.js' {
  declare module.exports: $Exports<'jsxstyle/InlineBlock'>;
}
declare module 'jsxstyle/InlineFlex.js' {
  declare module.exports: $Exports<'jsxstyle/InlineFlex'>;
}
declare module 'jsxstyle/lib/Addons.js' {
  declare module.exports: $Exports<'jsxstyle/lib/Addons'>;
}
declare module 'jsxstyle/lib/Color.js' {
  declare module.exports: $Exports<'jsxstyle/lib/Color'>;
}
declare module 'jsxstyle/lib/createCSS.js' {
  declare module.exports: $Exports<'jsxstyle/lib/createCSS'>;
}
declare module 'jsxstyle/lib/CSSDisplayNames.js' {
  declare module.exports: $Exports<'jsxstyle/lib/CSSDisplayNames'>;
}
declare module 'jsxstyle/lib/curry.js' {
  declare module.exports: $Exports<'jsxstyle/lib/curry'>;
}
declare module 'jsxstyle/lib/Display.js' {
  declare module.exports: $Exports<'jsxstyle/lib/Display'>;
}
declare module 'jsxstyle/lib/explodePseudoStyles.js' {
  declare module.exports: $Exports<'jsxstyle/lib/explodePseudoStyles'>;
}
declare module 'jsxstyle/lib/extractStyles.js' {
  declare module.exports: $Exports<'jsxstyle/lib/extractStyles'>;
}
declare module 'jsxstyle/lib/GlobalStylesheets.js' {
  declare module.exports: $Exports<'jsxstyle/lib/GlobalStylesheets'>;
}
declare module 'jsxstyle/lib/index.js' {
  declare module.exports: $Exports<'jsxstyle/lib/index'>;
}
declare module 'jsxstyle/lib/JsxstylePlugin.js' {
  declare module.exports: $Exports<'jsxstyle/lib/JsxstylePlugin'>;
}
declare module 'jsxstyle/lib/legacyAutoprefix.js' {
  declare module.exports: $Exports<'jsxstyle/lib/legacyAutoprefix'>;
}
declare module 'jsxstyle/lib/makeStyleComponentClass.js' {
  declare module.exports: $Exports<'jsxstyle/lib/makeStyleComponentClass'>;
}
declare module 'jsxstyle/lib/renameClass.js' {
  declare module.exports: $Exports<'jsxstyle/lib/renameClass'>;
}
declare module 'jsxstyle/lib/webpackLoader.js' {
  declare module.exports: $Exports<'jsxstyle/lib/webpackLoader'>;
}
declare module 'jsxstyle/Row.js' {
  declare module.exports: $Exports<'jsxstyle/Row'>;
}
declare module 'jsxstyle/Table.js' {
  declare module.exports: $Exports<'jsxstyle/Table'>;
}
declare module 'jsxstyle/TableCell.js' {
  declare module.exports: $Exports<'jsxstyle/TableCell'>;
}
declare module 'jsxstyle/TableRow.js' {
  declare module.exports: $Exports<'jsxstyle/TableRow'>;
}
declare module 'jsxstyle/tests/className.spec.js' {
  declare module.exports: $Exports<'jsxstyle/tests/className.spec'>;
}
declare module 'jsxstyle/tests/Color.spec.js' {
  declare module.exports: $Exports<'jsxstyle/tests/Color.spec'>;
}
declare module 'jsxstyle/tests/curry.spec.js' {
  declare module.exports: $Exports<'jsxstyle/tests/curry.spec'>;
}
declare module 'jsxstyle/tests/example.js' {
  declare module.exports: $Exports<'jsxstyle/tests/example'>;
}
declare module 'jsxstyle/tests/extractStyles.spec.js' {
  declare module.exports: $Exports<'jsxstyle/tests/extractStyles.spec'>;
}
declare module 'jsxstyle/tests/renameClass.spec.js' {
  declare module.exports: $Exports<'jsxstyle/tests/renameClass.spec'>;
}
declare module 'jsxstyle/tests/webpackLoader.spec.js' {
  declare module.exports: $Exports<'jsxstyle/tests/webpackLoader.spec'>;
}
declare module 'jsxstyle/tests/webpackLoaderNamespace.js' {
  declare module.exports: $Exports<'jsxstyle/tests/webpackLoaderNamespace'>;
}
